name: Build

on: [ workflow_dispatch, push ]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        arch: [ "arm", "arm64" ]

    name: Build For Android (libraries and apks)
    runs-on: namespace-profile-anglebuild
    steps:
      - uses: namespacelabs/nscloud-setup@v0
    
      - name: Setup CCache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          ccache_options: |
            max_size=30000MB
            compression=false
    
      - name: Get Angle
        uses: namespacelabs/nscloud-checkout-action@v5
        with:
          path: 'angle'
          fetch-depth: 1

      - name: Get & Install depot_tools
        run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH

      - name: Angle dependencies caches
        uses: actions/cache@v4
        with:
          key: angle-deps-${{ matrix.arch }}-${{ hashFiles('angle/DEPS') }}
          restore-keys: angle-deps-${{ matrix.arch }}-${{ hashFiles('angle/DEPS') }}
          path: |
            angle/.cipd
            angle/third_party
          
      - name: Bootstrap and Sync Angle
        run: |
          cd angle
          vpython3 scripts/bootstrap.py
          gclient sync --no-history -j$(nproc)

      - name: Make GN arg
        run: |
          cd angle
          mkdir -p out/Android-${{ matrix.arch }}
          
          echo "target_os = \"android\"
          target_cpu = \"${{ matrix.arch }}\"
          is_component_build = false
          is_debug = false
          angle_assert_always_on = false
          is_clang = true
          proprietary_codecs = true
          dcheck_always_on = false
          angle_force_thread_safety = false

          cc_wrapper=\"env CCACHE_SLOPPINESS=time_macros ccache\"

          android32_ndk_api_level = 30
          android64_ndk_api_level = 30

          symbol_level = 0
          strip_debug_info = true
          generate_debug_info = false
          enable_resource_allowlist_generation = false
          use_thin_lto = true
          
          angle_enable_vulkan = true
          angle_enable_vulkan_validation_layers = false

          angle_enable_essl = true
          angle_enable_glsl = true
          angle_enable_hlsl = false

          angle_enable_gl = false
          angle_enable_d3d9 = false
          angle_enable_d3d11 = false
          angle_enable_null = false
          angle_enable_metal = false
          angle_enable_swiftshader = false

          angle_expose_non_conformant_extensions_and_versions = true
          
          build_angle_deqp_tests = false
          " > out/Android-${{ matrix.arch }}/args.gn

          gn gen out/Android-${{ matrix.arch }} --threads=$(nproc)
          gn args out/Android-${{ matrix.arch }} --list --short 

      - name: Build Angle (libraries)
        run: |
          cd angle
          autoninja -j$(nproc) -C out/Android-${{ matrix.arch }}

      - name: Build Angle (apk)
        run: |
          cd angle
          autoninja -j$(nproc) -C out/Android-${{ matrix.arch }} angle_apks

      - name: Upload Build Outputs (apk)
        uses: actions/upload-artifact@v4
        with:
          name: apks-${{ matrix.arch }}
          path: | 
            angle/out/Android-${{ matrix.arch }}/apks

      - name: Upload Build Outputs (libs)
        uses: actions/upload-artifact@v4
        with:
          name: libs-${{ matrix.arch }}
          path: |
            angle/out/Android-${{ matrix.arch }}/*.so
            angle/out/Android-${{ matrix.arch }}/lib.unstripped
